# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  US-EAST-Prerequesties:
    # The type of runner that the job will run on
    runs-on: [us-east-1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Excuting Prerequesties in US EAST
      run: echo Excuting Prerequesties in US EAST

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        sleep 30

  US-EAST-TerraformBuild:
    needs: US-EAST-Prerequesties
    runs-on: [us-east-1]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Excuting Terraform in US EAST
      run: echo Terraform Operations in US EAST
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        sleep 30

  AP-SOUTH-Prerequesties:
    # The type of runner that the job will run on
    runs-on: [us-south-1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Excuting Prerequesties in AP SOUTH
      run: echo Excuting Prerequesties in AP SOUTH

    # Runs a set of commands using the runners shell
    - name: Prerequesties in AP SOUTH Progress
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        sleep 30

  AP-SOUTH-TerraformBuild:
    needs: AP-SOUTH-Prerequesties
    runs-on: [us-south-1]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Excuting Terraform in AP SOUTH
      run: echo Terraform Operations in AP SOUTH
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        sleep 30
